version: '3'

services:
  exchaindnode0:
    container_name: exchaindnode0
    image: "exchain/node"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-exchaind.log}
    volumes:
      - ./build:/exchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  exchaindnode1:
    container_name: exchaindnode1
    image: "exchain/node"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-exchaind.log}
    volumes:
      - ./build:/exchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  exchaindnode2:
    container_name: exchaindnode2
    image: "exchain/node"
    environment:
      - ID=2
      - LOG=${LOG:-exchaind.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/exchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  exchaindnode3:
    container_name: exchaindnode3
    image: "exchain/node"
    environment:
      - ID=3
      - LOG=${LOG:-exchaind.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/exchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

