version: '3'

services:
  okexchaindnode0:
    container_name: okexchaindnode0
    image: "okexchain/node"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-okexchaind.log}
    volumes:
      - ./build:/okexchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  okexchaindnode1:
    container_name: okexchaindnode1
    image: "okexchain/node"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-okexchaind.log}
    volumes:
      - ./build:/okexchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  okexchaindnode2:
    container_name: okexchaindnode2
    image: "okexchain/node"
    environment:
      - ID=2
      - LOG=${LOG:-okexchaind.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/okexchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  okexchaindnode3:
    container_name: okexchaindnode3
    image: "okexchain/node"
    environment:
      - ID=3
      - LOG=${LOG:-okexchaind.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/okexchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

