name: cosmos-sdk-ut

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: technote-space/get-diff-action@v5
        id: git_diff
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Build
        run: cd ./libs/cosmos-sdk/ && GOARCH=${{ matrix.go-arch }} LEDGER_ENABLED=false make build

  cosmos-sdk:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/setup-go@v2

      - name: cosmos-sdk 
        run: go list ./libs/cosmos-sdk/... |xargs go test -count=1 -tags='norace ledger test_ledger_mock' 
