name: ci-exchain-ut

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


jobs:
  cache:
    paths: 
      - coverage/
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: go mod tidy
        run:
          go mod tidy -compat=1.17
      - name: Cache go modules
        run:
          make go-mod-cache
      - name: Build
        run:
          make build
  app:
    name: app ut
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test app
        run: |
          set -ex
          path="./app/..."
          package_lines=`go list ${path}`
          cover_pkgs=`echo ${package_lines[@]} | sed 's/ /,/g'`
          go list ${path} |xargs go test -mod=readonly -coverpkg=${cover_pkgs} -timeout 8m -coverprofile=app_ut.out -covermode=atomic 
  libs:
    name: libs ut
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test libs
        run: |
          go list ./libs/... |xargs go test -mod=readonly -timeout 8m -coverprofile=./coverage/libs_ut.out -covermode=atomic -tags='norace ledger test_ledger_mock'
  x:
    name: x ut
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test x
        run: |
          go list ./x/... |xargs go test -mod=readonly -timeout 8m -coverprofile=./coverage/x_ut.out -covermode=atomic 

  coverage:
    name: upload coverage
    needs: ["app","libs","x"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test x
        run: |
          set -ex

          echo "--> Gather coverage:"
          ls ./coverage/*.out
          echo "mode: atomic" > coverage.txt
          for prof in $(ls ./coverage/*.out); do
            tail -n +2 "$prof" >> coverage.txt
          done

          echo "--> upload codecov:"
          bash <(curl -s https://codecov.io/bash) -f coverage.txt
  
