name: ci-exchain-ut

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: go mod tidy
        run:
          go mod tidy -compat=1.17
      - name: Cache go modules
        run:
          make go-mod-cache
      - name: Build
        run:
          make build
  app:
    name: app tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test app
        run: go list ./app/... |xargs go test -count=1
  libs:
    name: libs tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test libs
        run: go list ./libs/... |xargs go test -count=1 -tags='norace ledger test_ledger_mock'
  x:
    name: x tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test x
        run: go list ./x/... |xargs go test -count=1
  
