name: ci-exchain-ut

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: go mod tidy
        run:
          go mod tidy -compat=1.17
      - name: Cache go modules
        run:
          make go-mod-cache
      - name: Build
        run:
          make build
  app:
    name: app ut
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run Test exchain/app
        id: first-attempt
        run: |
          set -ex
          codePath="./app/..."
          go list ${codePath} |xargs go test -mod=readonly -timeout 8m -coverprofile=coverage.data -covermode=atomic
        continue-on-error: true

      - name: Run Test exchain/app Retry on error
        id: second-attempt
        if: steps.first-attempt.outcome != 'success'      
        run: |
          set -ex
          codePath="./app/..."
          go list ${codePath} |xargs go test -mod=readonly -timeout 8m -coverprofile=coverage.data -covermode=atomic

      - name: Upload code coverage
        run: |
          set -ex
          echo "mode: atomic" > coverage.txt
          tail -n +2 coverage.data >> coverage.txt
          bash <(curl -s https://codecov.io/bash) -f coverage.txt 
  x:
    name: x ut
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run Test exchain/x
        id: first-attempt
        run: |
          set -ex
          codePath="./x/..."
          go list ${codePath} |xargs go test -mod=readonly -timeout 8m -coverprofile=coverage.data -covermode=atomic 
        continue-on-error: true

      - name: Run Test exchain/x Retry
        id: second-attempt
        if: steps.first-attempt.outcome != 'success'     
        run: |
          set -ex
          codePath="./x/..."
          go list ${codePath} |xargs go test -mod=readonly -timeout 8m -coverprofile=coverage.data -covermode=atomic 

      - name: Upload code coverage
        run: |
          set -ex
          echo "mode: atomic" > coverage.txt
          tail -n +2 coverage.data >> coverage.txt
          bash <(curl -s https://codecov.io/bash) -f coverage.txt

  libstm:
    name: libs tendermint ut
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test exchain/libs
        id: first-attempt
        run: |
          set -ex
          codePath="./libs/tendermint/..."
          go list ${codePath} |xargs go test -timeout 30m -tags='norace ledger test_ledger_mock'
        continue-on-error: true

      - name: Go Test exchain/libs retry
        id: second-attempt
        if: steps.first-attempt.outcome != 'success'
        run: |
          set -ex
          codePath="./libs/tendermint/..."
          go list ${codePath} |xargs go test -timeout 30m -tags='norace ledger test_ledger_mock'

  libscosmos:
    name: libs cosmos ut
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test exchain/libs
        id: first-attempt
        run: |
          set -ex
          codePath="./libs/cosmos-sdk/..."
          go list ${codePath} |xargs go test -timeout 30m -tags='norace ledger test_ledger_mock'
        continue-on-error: true

      - name: Go Test exchain/libs retry
        id: second-attempt
        if: steps.first-attempt.outcome != 'success'
        run: |
          set -ex
          codePath="./libs/cosmos-sdk/..."
          go list ${codePath} |xargs go test -timeout 30m -tags='norace ledger test_ledger_mock'
  libsother:
    name: libs other ut
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test exchain/libs
        id: first-attempt
        run: |
          set -ex
          codePath="./libs/..."
          go list ${codePath} | grep -v "tendermint" | grep -v "cosmos-sdk"  |xargs go test -timeout 30m -tags='norace ledger test_ledger_mock'
        continue-on-error: true

      - name: Go Test exchain/libs retry
        id: second-attempt
        if: steps.first-attempt.outcome != 'success'
        run: |
          set -ex
          codePath="./libs/..."
          go list ${codePath} | grep -v "tendermint" | grep -v "cosmos-sdk" |xargs go test -timeout 30m -tags='norace ledger test_ledger_mock'
  
