name: ci-libs-ut

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


jobs:
  libs:
    name: libs ut
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test exchain/libs
        run: |
          set -ex
          codePath="./libs/..."
          go list ${codePath} |xargs go test -timeout 30m -tags='norace ledger test_ledger_mock'

  
