name: tendermint-ut 

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Go Test tendermint/libs/async
        run: go test -count=1 -ldflags -s $(go list ./libs/tendermint/... | grep libs/async)

      - name: Go Test tendermint/lite/
        run: go test -count=1 ./libs/tendermint/lite/...

      - name: Go Test tendermint/mempool/
        run: go test -count=1 ./libs/tendermint/mempool/...

      - name: Go Test tendermint/consensus/
        run: go test -count=1 ./libs/tendermint/consensus/...
