name: tm-db-ut

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  tm-db:
    name: tm-db tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test tm-db
        run: go test -count=1 ./libs/tm-db/...
