name: tendermint-ut

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/setup-go@v2
      - name: Set GOBIN
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
      - uses: actions/checkout@v2.3.4
      - name: install
        run: cd ./libs/tendermint && make install install_abci && cd -
      # Cache bin
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary

  tm-core:
    name: tm-core tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: test_tm_core 
        run: echo "noop test" 
  tm-consensus:
    name: tm-consensus tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test consensus/
        run: echo "abandon tm-consensus tests, move to libs tests" 
  tm-lite:
    name: tm-lite tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test lite/
        run:  echo "abandon tm-lite tests, move to libs tests" 
  tm-async:
    name: tm-async tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test libs/async
        run: echo "abandon tm-async tests, move to libs tests" 

  tm-mempool:
    name: tm-mempool tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test mempool/
        id: first-attempt
        run: echo "abandon tm-mempool tests, move to libs tests" 
        continue-on-error: true
      - name: Go Test mempool Retry again on failure
        id: second-attempt
        if: steps.first-attempt.outcome != 'success'
        run: echo "abandon tm-mempool Retry tests, move to libs tests" 

  test_abci_apps:
    name: abci_apps tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set GOBIN
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary
      - name: test_abci_apps
        run: echo "abandon abci_apps tests" 

  test_abci_cli:
    name: abci_cli tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set GOBIN
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary
      - run: echo "abandon abci_cli tests" 
