name: ut 

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Test
      run: | 
        go test -v ./libs/cosmos-sdk/...
        go test ./libs/iavl/... -mod=readonly -timeout 15m -short -race -coverprofile=coverage.txt -covermode=atomic
        go test ./libs/iavl/... -mod=readonly -timeout 15m
        go test -v ./libs/tendermint/... 
      env:
        LEDGER_ENABLED : true
