name: Lint
on: [pull_request]
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
